<p><em>Last Updated: August 1, 2014</em></p>
<p>  WhereWeAllMeet.com (the &quot;<u>Site</u>&quot;),  operated solely by The Man You Want, LLC. (&quot;<u>we</u>&quot; or &quot;<u>us</u>&quot;),  respects the privacy of our users and has developed this privacy policy (the  &quot;<u>Privacy Policy</u>&quot;) to articulate our commitment to protecting  your personal privacy.<br />
  The Privacy Policy is intended to describe for  you, as an individual who is a user of the Site or of the services offered on  the Site (collectively with the Site, the &quot;Services&quot;), the information  we collect, how that information may be used, with whom it may be shared, and  your choices about such uses and disclosures.<br />
  We encourage you to read this Privacy Policy  carefully when using the Services. By accessing the Services, you acknowledge  and agree that you have read, fully accept, and will abide by this Privacy  Policy.</p>
<p><strong>Information we collect about you.</strong><br />
  In general, we don't collect personally  identifiable information about you. We may collect personal information that  can identify you in combination with other information, such as your name and  e- mail address, and generally collect other information that does not identify  you, like interesting places you've visited.</p>
<p><strong>Information you provide. </strong>We may collect and store any information that you enter on the Site or  provide to us in some other manner, such as through using some of our Services.</p>
<p><strong>Private personally identifiable information</strong>. While we don't, at this time, ask for very many items that alone  would be considered personally identifiable information, the information we  collect may include items like your name, address, e-mail address and telephone  number.</p>
<p><strong>Public preference information and content</strong>. When you create an account and join the Site (becoming a  &quot;Member&quot;) you create a profile containing non-identifiable  information, such descriptive information about you including, for example,  your height. You can also upload photographs of yourself to your profile. The  Services also allow you to propose dates and share other information publicly.  To the extent you provide any information in those sections of the Services,  that information is entirely public, could be indexed by Internet search  engines and may be used by us for any purpose. As such, you should exercise  caution when revealing information in public aspects of the Services.</p>
<p>  <strong>Financial information</strong>. We do not currently collect financial information, such as your  payment method (valid credit card number, type, expiration date or other  financial information); that information is collected and stored by our third  party payment processing company (the &quot;Payment Processor&quot;), and use  and storage of that information is governed by the Payment Processor's  applicable terms of service and privacy policy.</p>
<p><strong>Demographic and usage information</strong>. We may collect and store demographic information, such as your  gender, age, information about your interests and activities and information  related to your use of the Services, such as dates you have responded to and  profiles you have viewed. This information is not personally identifiable by  itself, but may become so in combination with other information.</p>
<p><strong>Location information</strong>. To the extent you voluntarily opt to use any of our Services that  that are based on the location of Members and which may report on those  Members' current locations (the &quot;Location-Based Services&quot;), we may  collect and store information about your location at the time you use those  Location-Based Services. This information can come from a variety of sources  depending on the client you use to access the Services; for example, a mobile  phone may report its GPS location at the time the Location-Based Services are  used.</p>
<p><strong>Information from other sources. </strong>We may also periodically obtain both personal and non- personal  information about you from business partners, contractors and other third  parties, including third-party platforms (&ldquo;Third Party Platforms&rdquo;), and add it  to our account information or other information we have collected (for example,  we may collect information about you from our Payment Processor in order to  continue your account subscription). Examples of information that we may  receive include: updated address information, purchase history and additional  demographic information.</p>
<p><strong>Information about others. </strong>We may also collect and store personal information about other people  that you provide to us, such as their name, address and e-mail address. If you  use the Services to send others (friends, relatives, colleagues, etc.) a gift,  we may store your personal information, and the personal information of each  such recipient in order to process those requests or facilitate future  activities.</p>
<p><strong>Information collected using cookies and other  technologies</strong>. We use various technologies to collect  information from your computer and about your activities on the Services.<strong></strong></p>
<p><strong>Information collected automatically. </strong>We automatically collect information from your browser when you access  the Services. This information includes your IP address, your browser type and  language, access times, the content of any undeleted cookies that your browser  previously accepted from us (see &quot;Cookies&quot; below), and the referring  website address.</p>
<p><strong>Cookies. </strong>When you  access the Services, we may assign your computer one or more cookies, to  facilitate access to the Services and to personalize your experience. Through  the use of cookies, we also may automatically collect information about your  activity related to the Services, such as the web pages you visit, the links  you click, and the searches you conduct. Most browsers automatically accept  cookies, but you can usually modify your browser setting to decline cookies. If  you choose to decline cookies, please note that you may not be able to sign in  or use some of the interactive features offered by the Services.</p>
<p><strong>Other Technologies. </strong>We may use standard Internet technology, such as web beacons and other  similar technologies, to track your use of the Services. We also may include  web beacons in advertisements or promotional or other e-mail messages or to  determine whether messages have been opened and acted upon. The information we  obtain in this manner enables us to customize the Services. It also may enable  us to deliver targeted advertisements and to measure the overall effectiveness  of our online advertising, content, programming or other activities.</p>
<p><strong>Information collected by third parties</strong><br />
  We may allow third parties, including but not  limited to our authorized service providers, advertising companies, corporate  partners, and ad networks, to display advertisements through the Services.  These companies may use tracking technologies, such as cookies, to collect  information about users who view or interact with their advertisements. This  information may allow them to deliver targeted advertisements and gauge their  effectiveness.<br />
  When you use or connect to the Site or download a  Site mobile app by or through a Third Party Platform, such as Facebook or other  social networking site, you allow us to access and/or collect certain  information from your Third Party Platform profile/account (such as your  Facebook account) or via any cookies placed on your device by such Third Party  Platform as permitted by the terms of the agreement and your privacy settings  with the Third Party Platform. We will share such information with the Third  Party Platform for their use as permitted by the terms of the agreement and  your privacy setting with the Third Party Platform.<br />
  We will share some of the information we collect  from you upon install of the mobile app with vendors and other service  providers who are engaged by or working with us in connection with the  operation of the services we provide to you and/or for analytics purposes which  may require the reproduction and display of such information in an aggregated  and anonymized manner such that will not in any way identify you.</p>
<p><strong>Where information we collect goes</strong><br />
  When you provide us with personal information,  that information may be sent to servers located in the United States and other  countries around the world.</p>
<p><strong>How we use the information we collect</strong><br />
  Generally, we may use information that we collect  about you to: facilitate and enhance your use of the Services;<br />
  manage your account and provide you with customer  support;<br />
  perform research and analysis about your use of,  or interest in, the Site, Services, and content provided by us, or products, services  and content offered by others;<br />
  communicate with you by e-mail, postal mail,  telephone and/or mobile devices about products or services that may be of  interest to you either from us or other third parties;<br />
  develop and display content and advertising  tailored to your interests as reflected by your use of the Services;<br />
  verify your eligibility and deliver prizes in  connection with contests and sweepstakes; enforce our Terms of Use;<br />
  manage our business; and<br />
  perform functions as otherwise described to you  at the time of collection.</p>
<p><strong>Financial information</strong>. As stated above, we do not currently collect financial information,  as that information is collected and stored by our Payment Processor. However,  we may from time to time request and receive some of your financial information  from our Payment Processor for the purposes of completing transactions you have  initiated through the Services, enrolling you in discount, rebate, and other  programs in which you elect to participate, protecting against or identify possible  fraudulent transactions, and otherwise as needed to manage our business.</p>
<p><strong>With whom we share your information</strong><br />
  We want you to understand when and with whom we  may share personal or other information we have collected about you or your  activities while using our Services.</p>
<p><strong>Public information</strong>. Any information (i) you place in your Member profile, such as your  username, any photographs you upload, and information under the  &quot;Basics&quot; and &quot;About Me&quot; sections; (ii) about dates you  propose; or (iii) otherwise posted by you to a public portion of the Services,  is completely public and could be indexed by Internet search engines. As such,  by providing us with that information, you acknowledge that you have no  reasonable expectation of privacy in it and that it may be used for any  purpose. As noted above, you should exercise due care in revealing information  through these public portions of the Services.</p>
<p><strong>Other personal information</strong>. We do not share your personal information with others except as  indicated below or when we inform you and give you an opportunity to opt out of  having your personal information shared. We may share personal information  with:</p>
<p><strong>Authorized agents and service providers: </strong>We may share your personal information, which may include your name  and contact information (including e-mail address) with our authorized agents  and service providers that perform certain services on our behalf. These  services may include maintaining our servers, fulfilling subscription requests,  providing customer service and marketing assistance, performing business and  sales analysis, supporting the functionality of the Services, providing payment  fulfillment and reconciliation services, and supporting rewards programs,  surveys and other features. These agents and service providers may have access  to personal information needed to perform their functions but are not permitted  to share or use such information for any other purposes.</p>
<p><strong>Business partners: </strong>When you make purchases or engage in promotions offered through the  Services, we may share personal information with the businesses, such as Third  Party Platforms, with which we partner to offer you those products, services,  promotions, or rewards. When you elect to engage in a particular offer or  program, you authorize us to provide your e-mail address and other information  to the associated merchant, if any. We will always provide you with the opportunity  not to share information with these businesses.</p>
<p><strong>Other Situations: </strong>We also may disclose your information, including personal information:<br />
  In response to a subpoena or similar  investigative demand, a court order, or a request for cooperation from law  enforcement or other government agencies; to establish or exercise our legal  rights; to defend against legal claims; or as otherwise required by law. In  such cases, we may raise or waive any legal objection or right available to us.<br />
  When we believe disclosure is appropriate in  connection with efforts to investigate, prevent, or take other action regarding  illegal activity, suspected fraud or other wrongdoing; to protect and defend  the rights, property or safety of our company, our users, our employees, or  others; to comply with applicable law or cooperate with law enforcement; or to  enforce the Terns of Use or other agreements or policies.<br />
  Any third parties to whom we may disclose  personal information may have their own privacy policies that describe how they  use and disclose personal information. Those policies will govern use, handling  and disclosure of your personal information once we have shared it with those  third parties as described in this Privacy Policy. If you want to learn more  about their privacy practices, we encourage you to visit the websites of those  third parties. These entities or their servers may be located either inside or  outside the United States.</p>
<p><strong>Aggregated and non-personal information</strong>. We may share aggregated and non-personal information we collect  under any of the above circumstances. We may also share it with third parties  to develop and deliver targeted advertising through the Services and on  websites of third parties. We may combine non-personal information we collect  with additional non-personal information collected from other sources. We also  may share aggregated information with third parties, including advisors,  advertisers and investors, for the purpose of conducting general business  analysis. For example, we may tell advertisers the number of visitors to the  Site and the most popular features people have accessed. This information does  not contain any personal information and may be used to develop website content  and services that we hope you and other users will find of interest and to  target content and advertising.</p>
<p><strong>In the event of a merger, sale, or bankruptcy</strong><br />
  In the event that we or any portion of the business  represented by the Services, are acquired by or merged with a third party  entity, we reserve the right, in any of these or similar circumstances, to  transfer or assign any or all of the information we have collected as part of  such merger, acquisition, sale, or other change of control.<br />
  In the event of our bankruptcy, insolvency,  reorganization, receivership, or assignment for the benefit of creditors, or  the application of laws or equitable principles affecting creditors' rights  generally, we may not be able to control how your personal information is  treated, transferred, or used.</p>
<p><strong>Third-party websites</strong><br />
  Through the Services, you may be able to click on  a link to access other websites that do not operate under this Privacy Policy.  For example, if you click on a link to an external article, you may be taken to  a website that we do not control. These third-party websites may independently  solicit and collect information, including personal information, from you and,  in some instances, provide us with information about your activities on those  websites. We recommend that you consult the privacy policies of all third-party  websites you visit by clicking on the &quot;privacy&quot; link typically  located at the bottom of the webpage you are visiting.</p>
<p><strong>How you can access your information</strong><br />
  If you are a Member, you have the ability to  review and update the information you have provided us by logging into your  account and clicking on &quot;Settings&quot;. You can also review and update  information in your public profile by clicking on the &quot;Profile&quot; link.<br />
  You also can review and update that information  by contacting us at the e-mail address provided below in the &quot;How to  contact us&quot; section of this Privacy Policy.</p>
<p><strong>How you can remove your information</strong><br />
  <strong>Closing your account</strong>. If you are a Member, you may choose to resign and close your account  at any time by visiting the &quot;Settings&quot; page for your account. After  you close your account, you will not be able to sign in to the Services or  access any of the information you have provided us. Upon closing your account,  your public profile information will no longer be accessible from the Services,  but may still be cached by Internet search engines.<br />
  <strong>Retention of information </strong>. If you close your account, we may still retain certain information  associated with your account for analytical purposes and recordkeeping  integrity, as well as to prevent fraud, collect any fees owed, enforce our  terms and conditions, take actions we deem necessary to protect the integrity  of our web site or our users, or take other actions otherwise permitted by law.  Further, because of the complexities of the technology involved, we cannot  guarantee total or irrevocable deletion of your account information, and we  cannot provide you with any specific timelines for deletion. In addition, if  certain information has already been provided to third parties as described in  this Privacy Policy, retention of that information will be subject to those  third parties' policies.<br />
  <strong>Your choices about collection and use of your  information</strong><br />
  You can choose not to provide us with certain  information, but that may result in you being unable to use some features of  the Services. For example, such information may be required for you to:  register as a Member; participate in things like proposing dates and responding  to date proposals; participate in our Rewards Program and other contests or  promotions we may offer from time to time; ask questions; send messages to  Members; or initiate other transactions on through the Services.<br />
  If you are a Member, you can elect not to share  any of your profile information publicly by visiting your Settings page and  selecting to have your profile available only to users signed into the  Services. This does not prevent us from sharing your information with third  parties as specified above.<br />
  Further, to the extent we send commercial or  promotional e-mails to Members, you will be able to opt-out of receiving those  e-mails, either in your Settings or within the body of any such e-mail.<br />
  You may &quot;opt out&quot; of the collection of  your information for third party analytics purposes by following the directions  provided by our third party analytics vendor. If you &ldquo;opt out&rdquo; with our third  party analytics provider, that action is specific to the information we collect  specifically for that provider, and does not limit our ability to collect  information from you, under the terms of this privacy policy, for other  vendors.<br />
  In addition, if we have already provided your  information to a third party (such as a service provider) before you have  changed your preferences or updated your information, you may have to change  your preferences directly with that third party.<br />
  We may send you, as a Member, other types of  transactional and relationship e-mail communications, such as service  announcements, administrative notices, and surveys, without offering you the  opportunity to opt-out of receiving them, as our ability to communicate with  you in some instances is necessary for your use of the Services as a Member.<br />
  Please note that changing information in your account,  or otherwise opting-out of receipt of certain e-mail communications, will only  affect future activities or communications from us.</p>
<p><strong>How we protect your personal information</strong><br />
  We take appropriate security measures (including  physical, electronic and procedural measures) to help safeguard your personal  information from unauthorized access and disclosure. For example, only  authorized employees and third parties who have agreed to be bound by  confidentiality restrictions, such as consultants, may be permitted to access  personal information, and they may do so only for permitted business functions.  In addition, we use SSL encryption in the transmission of your sensitive  personal information between your system and ours, and we use firewalls to help  prevent unauthorized persons from gaining access to your personal information.<br />
  We want you to feel confident using the Services.  However, no system can be completely secure. Therefore, although we take steps  to secure your information, we do not promise, and you should not expect, that  your personal information, searches, or other communications will always remain  secure. Users should also take care with how they handle and disclose their  personal information and should avoid sending personal information through insecure  e-mail. Please refer to the Federal Trade Commission's website at <a href="http://www.ftc.gov/bcp/menus/consumer/data.shtm" target="_blank">http://www.ftc.gov/bcp/menus/consumer/data.shtm</a>for information about how to protect yourself against identity theft.</p>
<p><strong>Children's privacy</strong><br />
  Although  the Services are meant for a general audience, we restrict their use to  individuals age 18 and above. We do not knowingly seek or collect personal  information from children under the age of 13.</p>
<p><strong>Visiting the Site from outside the United States</strong><br />
  This Privacy Policy is intended to cover  collection of information from residents of the United States. If you are  accessing the Services from outside the United States, please be aware that  your information may be transferred to, stored, and processed in the United  States where our servers are located and our central database is operated. The  data protection and other laws of the United States and other countries might  not be as comprehensive as those in your country. Please be assured that we seek  to take reasonable steps to ensure that your privacy is protected. By using the  Services, you understand that your information may be transferred to our  facilities and those third parties with whom we share it as described in this  Privacy Policy.</p>
<p><strong>No rights of third parties</strong><br />
  This Privacy Policy does not create rights  enforceable by third parties or require disclosure of any personal information  relating to users of the Services.</p>
<p><strong>Changes to this Privacy Policy</strong><br />
  We will occasionally update this Privacy Policy  to reflect changes in our practices and in the Services. When we post changes  to this Privacy Policy, we will revise the &quot;last updated&quot; date at the  top of this Privacy Policy. If we make any material changes in the way we  collect, use, and/or share your personal information, we will notify you by  sending an e-mail to the e-mail address you most recently provided us in your  account, profile or registration (unless we do not have such an e-mail  address), and/or by prominently posting notice of the changes through the  Services. We recommend that you check the Services from time to time to inform  yourself of any changes in this Privacy Policy or any of our other policies.</p>
<p><strong>How to contact us</strong><br />
  If you have any questions about this Privacy  Policy or our information-handling practices, or if you would like to request  information about our disclosure of personal information to third parties for  their direct marketing purposes, please contact us by e-mail at  support@whereweallmeet.com or postal mail as follows:<br />
  Privacy Officer<br />
  The Man You Want, LLC.<br />
  5940 S. Rainbow Blvd.<br />
  Las Vegas, NV 89118</p>
