<?php

namespace Fuel\Migrations;

class Create_Countries
{
	public function up()
	{
		\DBUtil::create_table('countries', array(
			'id' => array('constraint' => 11, 'type' => 'int', 'auto_increment' => true, 'unsigned' => true),
			'name' => array('constraint' => 255, 'type' => 'varchar'),
			'code' => array('constraint' => 5, 'type' => 'varchar'),
			'created_at' => array('constraint' => 11, 'type' => 'int', 'null' => true),
			'updated_at' => array('constraint' => 11, 'type' => 'int', 'null' => true),

		), array('id'));

        \Model_Country::forge(array('name' => "Aruba", 'code' => "ABW"))->save();
        \Model_Country::forge(array('name' => "Afghanistan", 'code' => "AFG"))->save();
        \Model_Country::forge(array('name' => "Angola", 'code' => "AGO"))->save();
        \Model_Country::forge(array('name' => "Anguilla", 'code' => "AIA"))->save();
        \Model_Country::forge(array('name' => "Åland Islands", 'code' => "ALA"))->save();
        \Model_Country::forge(array('name' => "Albania", 'code' => "ALB"))->save();
        \Model_Country::forge(array('name' => "Andorra", 'code' => "AND"))->save();
        \Model_Country::forge(array('name' => "United Arab Emirates", 'code' => "ARE"))->save();
        \Model_Country::forge(array('name' => "Argentina", 'code' => "ARG"))->save();
        \Model_Country::forge(array('name' => "Armenia", 'code' => "ARM"))->save();
        \Model_Country::forge(array('name' => "American Samoa", 'code' => "ASM"))->save();
        \Model_Country::forge(array('name' => "Antarctica", 'code' => "ATA"))->save();
        \Model_Country::forge(array('name' => "French Southern Territories", 'code' => "ATF"))->save();
        \Model_Country::forge(array('name' => "Antigua and Barbuda", 'code' => "ATG"))->save();
        \Model_Country::forge(array('name' => "Australia", 'code' => "AUS"))->save();
        \Model_Country::forge(array('name' => "Austria", 'code' => "AUT"))->save();
        \Model_Country::forge(array('name' => "Azerbaijan", 'code' => "AZE"))->save();
        \Model_Country::forge(array('name' => "Burundi", 'code' => "BDI"))->save();
        \Model_Country::forge(array('name' => "Belgium", 'code' => "BEL"))->save();
        \Model_Country::forge(array('name' => "Benin", 'code' => "BEN"))->save();
        \Model_Country::forge(array('name' => "Bonaire, Sint Eustatius and Saba", 'code' => "BES"))->save();
        \Model_Country::forge(array('name' => "Burkina Faso", 'code' => "BFA"))->save();
        \Model_Country::forge(array('name' => "Bangladesh", 'code' => "BGD"))->save();
        \Model_Country::forge(array('name' => "Bulgaria", 'code' => "BGR"))->save();
        \Model_Country::forge(array('name' => "Bahrain", 'code' => "BHR"))->save();
        \Model_Country::forge(array('name' => "Bahamas", 'code' => "BHS"))->save();
        \Model_Country::forge(array('name' => "Bosnia and Herzegovina", 'code' => "BIH"))->save();
        \Model_Country::forge(array('name' => "Saint Barthélemy", 'code' => "BLM"))->save();
        \Model_Country::forge(array('name' => "Belarus", 'code' => "BLR"))->save();
        \Model_Country::forge(array('name' => "Belize", 'code' => "BLZ"))->save();
        \Model_Country::forge(array('name' => "Bermuda", 'code' => "BMU"))->save();
        \Model_Country::forge(array('name' => "Bolivia, Plurinational State of", 'code' => "BOL"))->save();
        \Model_Country::forge(array('name' => "Brazil", 'code' => "BRA"))->save();
        \Model_Country::forge(array('name' => "Barbados", 'code' => "BRB"))->save();
        \Model_Country::forge(array('name' => "Brunei Darussalam", 'code' => "BRN"))->save();
        \Model_Country::forge(array('name' => "Bhutan", 'code' => "BTN"))->save();
        \Model_Country::forge(array('name' => "Bouvet Island", 'code' => "BVT"))->save();
        \Model_Country::forge(array('name' => "Botswana", 'code' => "BWA"))->save();
        \Model_Country::forge(array('name' => "Central African Republic", 'code' => "CAF"))->save();
        \Model_Country::forge(array('name' => "Canada", 'code' => "CAN"))->save();
        \Model_Country::forge(array('name' => "Cocos (Keeling) Islands", 'code' => "CCK"))->save();
        \Model_Country::forge(array('name' => "Switzerland", 'code' => "CHE"))->save();
        \Model_Country::forge(array('name' => "Chile", 'code' => "CHL"))->save();
        \Model_Country::forge(array('name' => "China", 'code' => "CHN"))->save();
        \Model_Country::forge(array('name' => "Côte d'Ivoire", 'code' => "CIV"))->save();
        \Model_Country::forge(array('name' => "Cameroon", 'code' => "CMR"))->save();
        \Model_Country::forge(array('name' => "Congo, the Democratic Republic of the", 'code' => "COD"))->save();
        \Model_Country::forge(array('name' => "Congo", 'code' => "COG"))->save();
        \Model_Country::forge(array('name' => "Cook Islands", 'code' => "COK"))->save();
        \Model_Country::forge(array('name' => "Colombia", 'code' => "COL"))->save();
        \Model_Country::forge(array('name' => "Comoros", 'code' => "COM"))->save();
        \Model_Country::forge(array('name' => "Cape Verde", 'code' => "CPV"))->save();
        \Model_Country::forge(array('name' => "Costa Rica", 'code' => "CRI"))->save();
        \Model_Country::forge(array('name' => "Cuba", 'code' => "CUB"))->save();
        \Model_Country::forge(array('name' => "Curaçao", 'code' => "CUW"))->save();
        \Model_Country::forge(array('name' => "Christmas Island", 'code' => "CXR"))->save();
        \Model_Country::forge(array('name' => "Cayman Islands", 'code' => "CYM"))->save();
        \Model_Country::forge(array('name' => "Cyprus", 'code' => "CYP"))->save();
        \Model_Country::forge(array('name' => "Czech Republic", 'code' => "CZE"))->save();
        \Model_Country::forge(array('name' => "Germany", 'code' => "DEU"))->save();
        \Model_Country::forge(array('name' => "Djibouti", 'code' => "DJI"))->save();
        \Model_Country::forge(array('name' => "Dominica", 'code' => "DMA"))->save();
        \Model_Country::forge(array('name' => "Denmark", 'code' => "DNK"))->save();
        \Model_Country::forge(array('name' => "Dominican Republic", 'code' => "DOM"))->save();
        \Model_Country::forge(array('name' => "Algeria", 'code' => "DZA"))->save();
        \Model_Country::forge(array('name' => "Ecuador", 'code' => "ECU"))->save();
        \Model_Country::forge(array('name' => "Egypt", 'code' => "EGY"))->save();
        \Model_Country::forge(array('name' => "Eritrea", 'code' => "ERI"))->save();
        \Model_Country::forge(array('name' => "Western Sahara", 'code' => "ESH"))->save();
        \Model_Country::forge(array('name' => "Spain", 'code' => "ESP"))->save();
        \Model_Country::forge(array('name' => "Estonia", 'code' => "EST"))->save();
        \Model_Country::forge(array('name' => "Ethiopia", 'code' => "ETH"))->save();
        \Model_Country::forge(array('name' => "Finland", 'code' => "FIN"))->save();
        \Model_Country::forge(array('name' => "Fiji", 'code' => "FJI"))->save();
        \Model_Country::forge(array('name' => "Falkland Islands (Malvinas)", 'code' => "FLK"))->save();
        \Model_Country::forge(array('name' => "France", 'code' => "FRA"))->save();
        \Model_Country::forge(array('name' => "Faroe Islands", 'code' => "FRO"))->save();
        \Model_Country::forge(array('name' => "Micronesia, Federated States of", 'code' => "FSM"))->save();
        \Model_Country::forge(array('name' => "Gabon", 'code' => "GAB"))->save();
        \Model_Country::forge(array('name' => "United Kingdom", 'code' => "GBR"))->save();
        \Model_Country::forge(array('name' => "Georgia", 'code' => "GEO"))->save();
        \Model_Country::forge(array('name' => "Guernsey", 'code' => "GGY"))->save();
        \Model_Country::forge(array('name' => "Ghana", 'code' => "GHA"))->save();
        \Model_Country::forge(array('name' => "Gibraltar", 'code' => "GIB"))->save();
        \Model_Country::forge(array('name' => "Guinea", 'code' => "GIN"))->save();
        \Model_Country::forge(array('name' => "Guadeloupe", 'code' => "GLP"))->save();
        \Model_Country::forge(array('name' => "Gambia", 'code' => "GMB"))->save();
        \Model_Country::forge(array('name' => "Guinea", 'code' => "GNB"))->save();
        \Model_Country::forge(array('name' => "Equatorial Guinea", 'code' => "GNQ"))->save();
        \Model_Country::forge(array('name' => "Greece", 'code' => "GRC"))->save();
        \Model_Country::forge(array('name' => "Grenada", 'code' => "GRD"))->save();
        \Model_Country::forge(array('name' => "Greenland", 'code' => "GRL"))->save();
        \Model_Country::forge(array('name' => "Guatemala", 'code' => "GTM"))->save();
        \Model_Country::forge(array('name' => "French Guiana", 'code' => "GUF"))->save();
        \Model_Country::forge(array('name' => "Guam", 'code' => "GUM"))->save();
        \Model_Country::forge(array('name' => "Guyana", 'code' => "GUY"))->save();
        \Model_Country::forge(array('name' => "Hong Kong", 'code' => "HKG"))->save();
        \Model_Country::forge(array('name' => "Heard Island and McDonald Islands", 'code' => "HMD"))->save();
        \Model_Country::forge(array('name' => "Honduras", 'code' => "HND"))->save();
        \Model_Country::forge(array('name' => "Croatia", 'code' => "HRV"))->save();
        \Model_Country::forge(array('name' => "Haiti", 'code' => "HTI"))->save();
        \Model_Country::forge(array('name' => "Hungary", 'code' => "HUN"))->save();
        \Model_Country::forge(array('name' => "Indonesia", 'code' => "IDN"))->save();
        \Model_Country::forge(array('name' => "Isle of Man", 'code' => "IMN"))->save();
        \Model_Country::forge(array('name' => "India", 'code' => "IND"))->save();
        \Model_Country::forge(array('name' => "British Indian Ocean Territory", 'code' => "IOT"))->save();
        \Model_Country::forge(array('name' => "Ireland", 'code' => "IRL"))->save();
        \Model_Country::forge(array('name' => "Iran, Islamic Republic of", 'code' => "IRN"))->save();
        \Model_Country::forge(array('name' => "Iraq", 'code' => "IRQ"))->save();
        \Model_Country::forge(array('name' => "Iceland", 'code' => "ISL"))->save();
        \Model_Country::forge(array('name' => "Israel", 'code' => "ISR"))->save();
        \Model_Country::forge(array('name' => "Italy", 'code' => "ITA"))->save();
        \Model_Country::forge(array('name' => "Jamaica", 'code' => "JAM"))->save();
        \Model_Country::forge(array('name' => "Jersey", 'code' => "JEY"))->save();
        \Model_Country::forge(array('name' => "Jordan", 'code' => "JOR"))->save();
        \Model_Country::forge(array('name' => "Japan", 'code' => "JPN"))->save();
        \Model_Country::forge(array('name' => "Kazakhstan", 'code' => "KAZ"))->save();
        \Model_Country::forge(array('name' => "Kenya", 'code' => "KEN"))->save();
        \Model_Country::forge(array('name' => "Kyrgyzstan", 'code' => "KGZ"))->save();
        \Model_Country::forge(array('name' => "Cambodia", 'code' => "KHM"))->save();
        \Model_Country::forge(array('name' => "Kiribati", 'code' => "KIR"))->save();
        \Model_Country::forge(array('name' => "Saint Kitts and Nevis", 'code' => "KNA"))->save();
        \Model_Country::forge(array('name' => "Korea, Republic of", 'code' => "KOR"))->save();
        \Model_Country::forge(array('name' => "Kuwait", 'code' => "KWT"))->save();
        \Model_Country::forge(array('name' => "Lao People's Democratic Republic", 'code' => "LAO"))->save();
        \Model_Country::forge(array('name' => "Lebanon", 'code' => "LBN"))->save();
        \Model_Country::forge(array('name' => "Liberia", 'code' => "LBR"))->save();
        \Model_Country::forge(array('name' => "Libya", 'code' => "LBY"))->save();
        \Model_Country::forge(array('name' => "Saint Lucia", 'code' => "LCA"))->save();
        \Model_Country::forge(array('name' => "Liechtenstein", 'code' => "LIE"))->save();
        \Model_Country::forge(array('name' => "Sri Lanka", 'code' => "LKA"))->save();
        \Model_Country::forge(array('name' => "Lesotho", 'code' => "LSO"))->save();
        \Model_Country::forge(array('name' => "Lithuania", 'code' => "LTU"))->save();
        \Model_Country::forge(array('name' => "Luxembourg", 'code' => "LUX"))->save();
        \Model_Country::forge(array('name' => "Latvia", 'code' => "LVA"))->save();
        \Model_Country::forge(array('name' => "Macao", 'code' => "MAC"))->save();
        \Model_Country::forge(array('name' => "Saint Martin (French part)", 'code' => "MAF"))->save();
        \Model_Country::forge(array('name' => "Morocco", 'code' => "MAR"))->save();
        \Model_Country::forge(array('name' => "Monaco", 'code' => "MCO"))->save();
        \Model_Country::forge(array('name' => "Moldova, Republic of", 'code' => "MDA"))->save();
        \Model_Country::forge(array('name' => "Madagascar", 'code' => "MDG"))->save();
        \Model_Country::forge(array('name' => "Maldives", 'code' => "MDV"))->save();
        \Model_Country::forge(array('name' => "Mexico", 'code' => "MEX"))->save();
        \Model_Country::forge(array('name' => "Marshall Islands", 'code' => "MHL"))->save();
        \Model_Country::forge(array('name' => "Macedonia, the former Yugoslav Republic of", 'code' => "MKD"))->save();
        \Model_Country::forge(array('name' => "Mali", 'code' => "MLI"))->save();
        \Model_Country::forge(array('name' => "Malta", 'code' => "MLT"))->save();
        \Model_Country::forge(array('name' => "Myanmar", 'code' => "MMR"))->save();
        \Model_Country::forge(array('name' => "Montenegro", 'code' => "MNE"))->save();
        \Model_Country::forge(array('name' => "Mongolia", 'code' => "MNG"))->save();
        \Model_Country::forge(array('name' => "Northern Mariana Islands", 'code' => "MNP"))->save();
        \Model_Country::forge(array('name' => "Mozambique", 'code' => "MOZ"))->save();
        \Model_Country::forge(array('name' => "Mauritania", 'code' => "MRT"))->save();
        \Model_Country::forge(array('name' => "Montserrat", 'code' => "MSR"))->save();
        \Model_Country::forge(array('name' => "Martinique", 'code' => "MTQ"))->save();
        \Model_Country::forge(array('name' => "Mauritius", 'code' => "MUS"))->save();
        \Model_Country::forge(array('name' => "Malawi", 'code' => "MWI"))->save();
        \Model_Country::forge(array('name' => "Malaysia", 'code' => "MYS"))->save();
        \Model_Country::forge(array('name' => "Mayotte", 'code' => "MYT"))->save();
        \Model_Country::forge(array('name' => "Namibia", 'code' => "NAM"))->save();
        \Model_Country::forge(array('name' => "New Caledonia", 'code' => "NCL"))->save();
        \Model_Country::forge(array('name' => "Niger", 'code' => "NER"))->save();
        \Model_Country::forge(array('name' => "Norfolk Island", 'code' => "NFK"))->save();
        \Model_Country::forge(array('name' => "Nigeria", 'code' => "NGA"))->save();
        \Model_Country::forge(array('name' => "Nicaragua", 'code' => "NIC"))->save();
        \Model_Country::forge(array('name' => "Niue", 'code' => "NIU"))->save();
        \Model_Country::forge(array('name' => "Netherlands", 'code' => "NLD"))->save();
        \Model_Country::forge(array('name' => "Norway", 'code' => "NOR"))->save();
        \Model_Country::forge(array('name' => "Nepal", 'code' => "NPL"))->save();
        \Model_Country::forge(array('name' => "Nauru", 'code' => "NRU"))->save();
        \Model_Country::forge(array('name' => "New Zealand", 'code' => "NZL"))->save();
        \Model_Country::forge(array('name' => "Oman", 'code' => "OMN"))->save();
        \Model_Country::forge(array('name' => "Pakistan", 'code' => "PAK"))->save();
        \Model_Country::forge(array('name' => "Panama", 'code' => "PAN"))->save();
        \Model_Country::forge(array('name' => "Pitcairn", 'code' => "PCN"))->save();
        \Model_Country::forge(array('name' => "Peru", 'code' => "PER"))->save();
        \Model_Country::forge(array('name' => "Philippines", 'code' => "PHL"))->save();
        \Model_Country::forge(array('name' => "Palau", 'code' => "PLW"))->save();
        \Model_Country::forge(array('name' => "Papua New Guinea", 'code' => "PNG"))->save();
        \Model_Country::forge(array('name' => "Poland", 'code' => "POL"))->save();
        \Model_Country::forge(array('name' => "Puerto Rico", 'code' => "PRI"))->save();
        \Model_Country::forge(array('name' => "Korea, Democratic People's Republic of", 'code' => "PRK"))->save();
        \Model_Country::forge(array('name' => "Portugal", 'code' => "PRT"))->save();
        \Model_Country::forge(array('name' => "Paraguay", 'code' => "PRY"))->save();
        \Model_Country::forge(array('name' => "Palestine, State of", 'code' => "PSE"))->save();
        \Model_Country::forge(array('name' => "French Polynesia", 'code' => "PYF"))->save();
        \Model_Country::forge(array('name' => "Qatar", 'code' => "QAT"))->save();
        \Model_Country::forge(array('name' => "Réunion", 'code' => "REU"))->save();
        \Model_Country::forge(array('name' => "Romania", 'code' => "ROU"))->save();
        \Model_Country::forge(array('name' => "Russian Federation", 'code' => "RUS"))->save();
        \Model_Country::forge(array('name' => "Rwanda", 'code' => "RWA"))->save();
        \Model_Country::forge(array('name' => "Saudi Arabia", 'code' => "SAU"))->save();
        \Model_Country::forge(array('name' => "Sudan", 'code' => "SDN"))->save();
        \Model_Country::forge(array('name' => "Senegal", 'code' => "SEN"))->save();
        \Model_Country::forge(array('name' => "Singapore", 'code' => "SGP"))->save();
        \Model_Country::forge(array('name' => "South Georgia and the South Sandwich Islands", 'code' => "SGS"))->save();
        \Model_Country::forge(array('name' => "Saint Helena, Ascension and Tristan da Cunha", 'code' => "SHN"))->save();
        \Model_Country::forge(array('name' => "Svalbard and Jan Mayen", 'code' => "SJM"))->save();
        \Model_Country::forge(array('name' => "Solomon Islands", 'code' => "SLB"))->save();
        \Model_Country::forge(array('name' => "Sierra Leone", 'code' => "SLE"))->save();
        \Model_Country::forge(array('name' => "El Salvador", 'code' => "SLV"))->save();
        \Model_Country::forge(array('name' => "San Marino", 'code' => "SMR"))->save();
        \Model_Country::forge(array('name' => "Somalia", 'code' => "SOM"))->save();
        \Model_Country::forge(array('name' => "Saint Pierre and Miquelon", 'code' => "SPM"))->save();
        \Model_Country::forge(array('name' => "Serbia", 'code' => "SRB"))->save();
        \Model_Country::forge(array('name' => "South Sudan", 'code' => "SSD"))->save();
        \Model_Country::forge(array('name' => "Sao Tome and Principe", 'code' => "STP"))->save();
        \Model_Country::forge(array('name' => "Suriname", 'code' => "SUR"))->save();
        \Model_Country::forge(array('name' => "Slovakia", 'code' => "SVK"))->save();
        \Model_Country::forge(array('name' => "Slovenia", 'code' => "SVN"))->save();
        \Model_Country::forge(array('name' => "Sweden", 'code' => "SWE"))->save();
        \Model_Country::forge(array('name' => "Swaziland", 'code' => "SWZ"))->save();
        \Model_Country::forge(array('name' => "Sint Maarten (Dutch part)", 'code' => "SXM"))->save();
        \Model_Country::forge(array('name' => "Seychelles", 'code' => "SYC"))->save();
        \Model_Country::forge(array('name' => "Syrian Arab Republic", 'code' => "SYR"))->save();
        \Model_Country::forge(array('name' => "Turks and Caicos Islands", 'code' => "TCA"))->save();
        \Model_Country::forge(array('name' => "Chad", 'code' => "TCD"))->save();
        \Model_Country::forge(array('name' => "Togo", 'code' => "TGO"))->save();
        \Model_Country::forge(array('name' => "Thailand", 'code' => "THA"))->save();
        \Model_Country::forge(array('name' => "Tajikistan", 'code' => "TJK"))->save();
        \Model_Country::forge(array('name' => "Tokelau", 'code' => "TKL"))->save();
        \Model_Country::forge(array('name' => "Turkmenistan", 'code' => "TKM"))->save();
        \Model_Country::forge(array('name' => "Timor", 'code' => "TLS"))->save();
        \Model_Country::forge(array('name' => "Tonga", 'code' => "TON"))->save();
        \Model_Country::forge(array('name' => "Trinidad and Tobago", 'code' => "TTO"))->save();
        \Model_Country::forge(array('name' => "Tunisia", 'code' => "TUN"))->save();
        \Model_Country::forge(array('name' => "Turkey", 'code' => "TUR"))->save();
        \Model_Country::forge(array('name' => "Tuvalu", 'code' => "TUV"))->save();
        \Model_Country::forge(array('name' => "Taiwan, Province of China", 'code' => "TWN"))->save();
        \Model_Country::forge(array('name' => "Tanzania, United Republic of", 'code' => "TZA"))->save();
        \Model_Country::forge(array('name' => "Uganda", 'code' => "UGA"))->save();
        \Model_Country::forge(array('name' => "Ukraine", 'code' => "UKR"))->save();
        \Model_Country::forge(array('name' => "United States Minor Outlying Islands", 'code' => "UMI"))->save();
        \Model_Country::forge(array('name' => "Uruguay", 'code' => "URY"))->save();
        \Model_Country::forge(array('name' => "United States", 'code' => "USA"))->save();
        \Model_Country::forge(array('name' => "Uzbekistan", 'code' => "UZB"))->save();
        \Model_Country::forge(array('name' => "Holy See (Vatican City State)", 'code' => "VAT"))->save();
        \Model_Country::forge(array('name' => "Saint Vincent and the Grenadines", 'code' => "VCT"))->save();
        \Model_Country::forge(array('name' => "Venezuela, Bolivarian Republic of", 'code' => "VEN"))->save();
        \Model_Country::forge(array('name' => "Virgin Islands, British", 'code' => "VGB"))->save();
        \Model_Country::forge(array('name' => "Virgin Islands, U.S.", 'code' => "VIR"))->save();
        \Model_Country::forge(array('name' => "Viet Nam", 'code' => "VNM"))->save();
        \Model_Country::forge(array('name' => "Vanuatu", 'code' => "VUT"))->save();
        \Model_Country::forge(array('name' => "Wallis and Futuna", 'code' => "WLF"))->save();
        \Model_Country::forge(array('name' => "Samoa", 'code' => "WSM"))->save();
        \Model_Country::forge(array('name' => "Yemen", 'code' => "YEM"))->save();
        \Model_Country::forge(array('name' => "South Africa", 'code' => "ZAF"))->save();
        \Model_Country::forge(array('name' => "Zambia", 'code' => "ZMB"))->save();
        \Model_Country::forge(array('name' => "Zimbabwe", 'code' => "ZWE"))->save();

	}

	public function down()
	{
		\DBUtil::drop_table('countries');
	}
}