<p><em>Last Updated: August 1, 2014</em></p>
<p>  In order to use the Services, you must agree to  be bound by these Terms of Use (the &quot;<u>Terms</u>&quot;) and by our  Privacy Policy, whether or not you register as a member (a &quot;<u>Member</u>&quot;). <strong>If you object to anything in these Terms or the Privacy Policy, you are  prohibited from using the Services.</strong><br />
  These Terms and Privacy Policy are subject to  change by us at any time, effective upon posting through the Services; by  accessing the Services after any such change, you accept the Terms as modified.<br />
  The Services are currently under intense  development and different features will be rolled out over the coming months.  Some parts of these Terms refer to functionality that have not yet been  implemented or deployed. Once such functions are available for use, by  continuing to use the Services you agree that those parts of these Terms shall  go into effect.  </p>
<p>1.<strong>Eligibility</strong>.<strong></strong></p>
<p>  1.<strong>Adult  Users Only</strong>. The Services are not intended for individuals under 18 years of  age. <strong>If you are under 18, you are strictly prohibited from using the  Services</strong>, and you may not access any features that allow you to provide  information to us or communicate and share information with other users.  Accordingly, you represent and warrant that you are 18 years of age or older  and that you have the right, authority and capacity to enter agree to and abide  by these Terms.<br />
  2.<strong>No  Criminal History</strong>. By accessing the Services, you represent and warrant that  you have never been convicted of a felony and are not required to register as a  sex offender with any government entity. We do not currently conduct criminal  background searches on Members. However, we reserve the right to conduct a  criminal background check, at any time and using available public records, to  confirm compliance with these Terms.<br />
  3.<strong>Void  Where Prohibited. </strong>You are responsible for ensuring that your use of the  Services complies with all laws, rules and regulations applicable to you. These  Terms are void and use of the Services is not permitted where such use is  prohibited.</p>
<p>  2.<strong>Use  of the Services</strong>.<strong></strong></p>
<p>  1.<strong>Personal  Safety</strong>. Your security and safety are paramount to us. The Services  naturally promote sharing of personal information among Members and non-  Members. You should be aware that some of your profile information as a Member  shall be public, could be indexed by Internet search engines and may be used  for any purpose. We strongly advise you to use the utmost caution before  sharing any personally identifiable information with others, or with any other  users, including Members. We do not and cannot assure that it is safe for you  to have direct contact with any other individual that you come into contact  with through the Services. If you believe that any individual is harassing you  or is otherwise using personal information about you for unlawful purposes, we  encourage you to first inform local law enforcement authorities and then to  contact us at support@whereweall.com so that we may take appropriate action to  block further use of the Services by any individuals who may have accessed them  for improper purposes.<br />
  2.<strong>Unique  and Accurate Profile Information </strong>.<strong></strong><br />
  i.You  agree that, as a Member, you will create and use only one unique profile.<br />
  ii.You agree that you will be truthful, accurate and complete in the  information presented in your Member profile.<br />
  iii.You agree that you will maintain any photos posted to your Member  profile to within two (2) years of the date taken.<br />
  3.<strong>Use  of Information Provided by Other Users </strong>.<strong></strong><br />
  i.You  agree to use any information (personal or otherwise) provided to you by  Members, or otherwise through the Services, in a lawful and responsible manner.  You agree that you will not use information about Members for any reason  without the express prior consent of the Member that has provided such  information to you.<br />
  ii.You  further agree not to engage in advertising to, or solicitation of, other  Members, including but not limited to: solicitation or advertising through the  Services; solicitation to attend parties or other social functions for  commercial purposes; solicitation to network for commercial purposes; and  transmission of chain letters or junk messages and email.<br />
  4.<strong>Code of Conduct </strong>. By accessing the Services, you agree to the  following code of conduct:<br />
  i.You  will not publish, display or use (hereinafter &quot;<u>post</u>&quot;) any  defamatory, abusive, obscene, profane, threatening, harassing, sexually  oriented, racially offensive, discriminatory or otherwise offensive or illegal  material.<br />
  ii.You  will treat all fellow Members with dignity and respect.<br />
  iii.You  will notify us promptly of any Member's violation of these Terms.<br />
  iv.You will not include in your Member profile any telephone numbers,  street addresses, last names, URLs, email addresses or other contact  information; if you do so, it is at your own risk and we assume no  responsibility for use of such information.<br />
  v.You will not impersonate any person or entity.<br />
  vi.You will not &quot;stalk&quot; or otherwise harass any Member or  other individual accessing the Services.<br />
  vii.You will not express or imply that any statements you make are  endorsed by us without specific prior written consent.<br />
  viii.You  will not use manual or automatic processes to retrieve, index, datamine, or in  any way reproduce or circumvent the navigational structure or presentation of  the Services or their contents. This prohibition does not include standard  indexing by Internet search engines, which hereby is explicitly permitted.<br />
  ix.You will not remove any copyright, trademark or other proprietary  rights notices displayed through the Services.<br />
  x.You  will not post, distribute or reproduce in any way any copyrighted material,  trademarks, or other proprietary information without obtaining the prior  consent of the owner of such proprietary rights.<br />
  xi.You will not interfere with or disrupt the Services or the servers  or networks connected to the Services.<br />
  xii.You  will not post, email or otherwise transmit any material that contains software  viruses or any other computer code, files or programs designed to interrupt,  destroy or limit the functionality of any computer software or hardware or  telecommunications equipment.<br />
  xiii.You will not forge headers or otherwise manipulate identifiers in  order to disguise the origin of any information transmitted through the  Services.<br />
  xiv.You  will not &quot;frame&quot; or &quot;mirror&quot; any part of the Services  without our prior written authorization. You also shall not use metatags or  code or other devices containing any reference to the Services in order to  direct any person to any other website for any purpose.<br />
  xv.You  will not modify, adapt, sublicense, translate, sell, reverse engineer,  decipher, decompile or otherwise disassemble any portion of the Services or any  software used on or for the Services, or cause or assist others to do so.<br />
  5.<strong>Location-Based  Services</strong>. We may offer features that are based on the location of Members  and which may report on those Members' current locations (the &quot; <u>Location-Based  Services</u>&quot;). Use of Location-Based Services is solely at your  discretion. Should you use Location-Based Services, you consent to collection  and dissemination of your location information through the Services. Under no  circumstances shall we be liable for claims or for any damages there from,  arising out of your informed decision to disseminate your location information  together with your profile information through the Services.<br />
  6.<strong>Commercial  Use</strong>. The Services are generally for the use of individual Members only.  However, from time to time, we may approve commercial use of the Services  through corporate partnerships and agreements. Unless specifically authorized  for commercial use by us under such an arrangement, organizations, companies,  and/or businesses may not become Members and should not use the Services for  any purpose. Illegal and/or unauthorized uses of the Services, including  collecting usernames and/or email addresses of Members by electronic or other  means for the purpose of sending unsolicited email, are prohibited.<br />
  7.<strong>Compliance  with Applicable Laws</strong>. Your use of the Services, including but not limited  to any content you post, must be and shall be in accordance with any and all  laws and regulations that apply to you and your use of the Services.<br />
  8.<strong>Disclaimers  of Responsibility for User Actions </strong>.<strong></strong><br />
  i.<strong>You  are solely responsible for your interactions and arrangements with other  individuals. </strong>You understand that we do not, in any way, screen individuals,  including Members, nor do we inquire into the backgrounds of Members or attempt  to verify their statements. We make no representations or warranties as to (i)  the conduct of Members, (ii) Members' compatibility with current or future  Members, (iii) any information concerning any venues, dates (proposed,  accepted, or otherwise), schedules or events suggested by Members or otherwise  through the Services. We do not verify or check any arrangements, including  proposed dates or schedules, on behalf of Members, and we therefore make no  guarantees about such dates or schedules. In no event shall we be liable for  any damages whatsoever, whether direct, indirect, general, special,  compensatory, consequential, and/or incidental, arising out of or relating to  the conduct of you or anyone else in connection with the Services, including,  without limitation, bodily injury, emotional distress, and any damages  resulting in any way from communications or meetings with Members or persons  you may otherwise meet through the Services. As such, you agree to take  reasonable precautions and exercise the utmost personal care in all  interactions with other Members or any other individual you come into contact  with through the Services, particularly if you decide to meet such Members or  individuals in person. In addition, you agree to review our Dating Safety Tips.  You understand and agree that we make no guarantees, express or implied,  regarding the provenance of, or your compatibility with, individuals you meet  through the Services. For example, you should not, under any circumstances,  provide your financial information<strong></strong><br />
  (e.g., credit card or bank account numbers) to  other individuals.<br />
ii.<strong>No  Reliance on Content</strong>. Opinions, advice, statements, offers, or other  information or content made available through the Services are those of their  respective authors and should not necessarily be relied upon. Such authors are  solely responsible for such content. We do not: (i) guarantee the accuracy,  completeness, or usefulness of any information on the Services or (ii) adopt,  endorse or accept responsibility for the accuracy or reliability of any  opinion, advice, or statement made by any party that appears on the Services.  Under no circumstances will we or our affiliates be responsible for any loss or  damage resulting from your reliance on information or other content posted  through the Services or transmitted to or by any Members.</p>
<p>  3.<strong>Reservation  of Rights</strong>.<strong></strong></p>
<p>  1.<strong>Right  to Terminate or Deny Service</strong>. You understand that we, at our sole  discretion, at any time, for any reason or no reason whatsoever, can deny or  block any user from the Services and terminate any user's account if he/she is  a Member.<br />
  2.<strong>Right  to Request Information</strong>. You understand that we have the right to request  complete, accurate and current information confirming eligibility for  subscription and/or membership and you agree to provide that information in  response to such a request.<br />
  3.<strong>Rights  to Disclose</strong>.<strong></strong><br />
  i.<strong>Disclosure  by Law</strong>. You acknowledge and agree that we have the right to disclose  information you provide if required to do so by law at the request of a third  party, or if we, in our sole discretion, believe that disclosure is reasonable  to (1) comply with the law, request or orders from law enforcement, or any  legal process (whether or not such disclosure is required by applicable law);  (2) protect or defend our, or a third party's, rights or property; or (3)  protect someone's health or safety, such as when harm or violence against any person  (including a user or Member) is threatened.<br />
  ii.<strong>Disclosure  to Protect Abuse Victims</strong>. Notwithstanding any other provision of these  Terms or the Privacy Policy, we reserve the right, but have no obligation, to  disclose any information that you submit, if in our sole opinion, we suspect or  have reason to suspect, that the information involves a party who may be the  victim of abuse in any form. Abuse may include, without limitation, elder  abuse, child abuse, spousal abuse, neglect, or domestic violence. Information  may be disclosed to authorities that we, in our sole discretion, deem  appropriate to handle such disclosure. Appropriate authorities may include,  without limitation, law enforcement agencies, child protection agencies, or  court officials.<br />
  4.<strong>Right  to Review Content; No Duty to Monitor</strong>. You acknowledge and agree that we  have no duty whatsoever to prescreen, control, monitor or edit the content  posted by Members and we are not liable for content that is provided by others.  However, you understand and agree that we may, but are not required to, review,  edit and delete any content, email, messages, photos, dates or profiles that,  in our sole judgment and discretion: (i) violate these Terms; (ii) may be  offensive, disturbing, unsafe, or illegal; or (iii) may violate any rights of  other Members or third parties.<strong></strong><br />
  5.<strong>Right  to Change Services</strong>. You acknowledge and agree that we may from time to time  modify, change, suspend or discontinue, temporarily or permanently, in whole or  in part, any aspect or feature of the Services without notice to you, including  changes to usage and to access procedures. You acknowledge and agree that we  shall not be liable to you or any third party for any such modification,  change,<br />
  suspension or discontinuance.<br />
6.<strong>Right  to Conduct Research; Informed Consent </strong>. By accessing the Services, you  agree to allow us to anonymously collect and use information from you and your  experience with the Services to conduct research about the Services and to  improve the products and user experience therein. All such information  collection and use will be in accordance with our Privacy Policy.<strong></strong></p>
<p>  4.<strong>Account  Security</strong>.<strong></strong></p>
<p>  1.<strong>User  Obligations </strong>.<strong></strong><br />
  i.You  understand and agree that you are responsible for maintaining the  confidentiality and security of the username and password that you designate  during the process of becoming a Member, and you are fully responsible for  anything that occurs under your username and password.<br />
  ii.You  agree to (1) immediately notify us of any unauthorized use of your username or  password or any other breach of security and (2) ensure that you exit from your  account at the end of each session. You acknowledge and agree that we will not  be liable for any loss or damage arising from your failure to comply with this  provision.<br />
  iii.You  agree to use extra care when accessing your account from a public or shared  computer, so that others are not able to view or record your password or other  personal information. If you share your computer with others, you may wish to  consider disabling your auto-sign in feature.<br />
2.<strong>Our  Obligations </strong>. We use industry-standard techniques to safeguard your account  information. However, perfect security is not possible on the Internet, and  therefore we cannot and do not guarantee that information provided to us will  not become public under any circumstances. This is particularly true for any  information you provide on public areas of the website, including public  profile information, with is fully public, may be indexed by Internet search  engines and may be used for any purpose.</p>
<p>  5.<strong>Proprietary  Rights; Use License </strong>.<strong></strong></p>
<p>  1.<strong>Ownership</strong>.  We and our licensors own and retain all proprietary rights in the Services. The  Services may contain the copyrighted material, trademarks, and other  proprietary information of us and our licensors (the &quot;<u>Site Content</u>&quot;).  Except for Site Content that is in the public domain or for which permission  has been provided, you may not copy, modify, publish, transmit, distribute,  perform, display, or sell any Site Content.<br />
  2.<strong>Use  License </strong>. Subject to these Terms, we grant to you a limited, revocable,  non- exclusive, fully paid license to access the Site Content, for the sole and  limited purpose of facilitating your use of the Services.<br />
  3.<strong>User  Content </strong>. You acknowledge and agree that if you use the Services to  contribute content (such as profile information, comments, responses, etc.)  (&quot;<u>User Content</u>&quot;), you hereby do and shall grant us a  non-exclusive, worldwide, royalty- free, transferable, sublicensable right to  use, modify, reproduce, distribute, prepare derivative works of, display,  publish, perform and otherwise fully exploit such User Content (including all  related intellectual property rights) in any media format, through any media  channel, for any purpose and to allow others to do so. You also hereby do and  shall grant each user of the Services a non-exclusive license to access your  User Content through the Services and to use such User Content as permitted by  the Services and under these Terms.<br />
  You represent, warrant and agree that you will  not contribute any User Content that:<br />
&middot;infringes, violates or otherwise interferes with any copyright or  trademark of another party;<br />
&middot;reveals any trade secret, unless you own the trade secret or have the  owner's permission to disclose it;<br />
&middot;infringes any intellectual property right of another or the privacy or  publicity rights of another;<br />
&middot;is libelous, defamatory, obscene, pornographic, abusive, indecent,  threatening, harassing, hateful, offensive or otherwise violates any law or  right of any third party; or<br />
&middot;may contain a virus, trojan horse, worm, time bomb or other computer  programming routine or engine that is intended to damage, detrimentally  interfere with, surreptitiously intercept or expropriate any system, data or  information.</p>
<p>  6.<strong>Copyright  Policy</strong>. </p>
<p>If you are a copyright owner or an agent thereof and believe that  any content on the Services infringes upon your copyrights, you may submit a  notification pursuant to the Digital Millennium Copyright Act by providing our  Copyright Agent for notice of claims of copyright infringement (The Man You  Want, LLC Legal, 5940 S. Rainbow Blvd., Las Vegas, NV 89118) with the following  information in writing:<br />
  1.A  physical or electronic signature of a person authorized to act on behalf of the  owner of an exclusive right that is allegedly infringed;<br />
  2.Identification of the copyrighted work claimed to have been  infringed, or, if multiple copyrighted works are covered by a single  notification, a representative list of such works;<br />
  3.Identification  of the material that is claimed to be infringing or to be the subject of  infringing activity and that is to be removed or access to which is to be  disabled and information reasonably sufficient to permit the service provider  to locate the material;<br />
  4.Information reasonably sufficient to permit us to contact you, such  as an address, telephone number, and, if available, an electronic mail;<br />
  5.A statement that you have a good faith belief that use of the  material in the manner complained of is not authorized by the copyright owner,  its agent, or the law; and<br />
  6.A statement that the information in the notification is accurate,  and under penalty of perjury, that you are authorized to act on behalf of the  owner of an exclusive right that is allegedly infringed.</p>
<p>  7.<strong>Membership </strong>. </p>
<p>You may become a Member at no cost. As a Member, you will have the  ability to use some, but not all, of the available features of the Services. In  order to access additional features, you must become a paying subscriber.</p>
<p>  8.<strong>Subscriptions  and Billing </strong>.<strong></strong></p>
<p>  1.<strong>Subscription  Plans and Policies </strong>. Please see Subscribe for a description of the current  subscription plans and prices. Please note that the Subscription Policies that  are disclosed to you in subscribing to the Services are deemed part of these  Terms. Please see Billing Details for a description of such policies. For the  purposes of these Terms, the term &quot;Member&quot; includes subscribers,  unless usage indicates otherwise. From time to time, we may remove the profiles  of non-subscribers.<br />
  2.<strong>Billing </strong>. We use a third-party payment processor (the &quot;<u>Payment Processor</u>&quot;)  to bill you through an online account (your &quot; <u>Billing Account</u>&quot;)  for use of the Services as a subscriber. The processing of payments will be  subject to the terms, conditions and privacy policies of the Payment Processor  in addition to these Terms. We are not responsible for error by the Payment  Processor. By subscribing, you agree to pay us, through the Payment Processor,  all charges at the prices then in effect for any use of<br />
  the Services in accordance with the subscription  plan that you have selected using your Billing Account, and you authorize us,  through the Payment Processor, to charge your chosen payment provider (your  &quot;<u>Payment Method</u>&quot;). You agree to make payment using that  selected Payment Method. We reserve the right to correct any errors or mistakes  that it makes even if it has already requested or received payment.<br />
  3.<strong>Payment  Method </strong>. The terms of your payment will be based on your Payment Method and  may be determined by agreements between you and the financial institution,  credit card issuer or other provider of your chosen Payment Method. If we,  through the Payment Processor, do not receive payment from you, you agree to  pay all amounts due on your Billing Account upon demand.<br />
  4.<strong>Recurring  Billing </strong>. Most subscription plans to the Services consist of an initial  period, for which there is a one-time charge, followed by recurring period  charges as agreed to by you. By choosing a recurring subscription plan, you  acknowledge that your subscription has an initial and recurring payment feature  and you accept responsibility for all recurring charges prior to cancellation.  WE MAY SUBMIT PERIODIC CHARGES (E.G., MONTHLY) WITHOUT FURTHER AUTHORIZATION  FROM YOU, UNTIL YOU PROVIDE PRIOR NOTICE (RECEIPT OF WHICH IS CONFIRMED BY US)  THAT YOU HAVE TERMINATED THIS AUTHORIZATION OR WISH TO CHANGE YOUR PAYMENT  METHOD. SUCH NOTICE WILL NOT AFFECT CHARGES SUBMITTED BEFORE WE REASONABLY  COULD ACT. TO TERMINATE YOUR AUTHORIZATION OR CHANGE YOUR PAYMENT METHOD, GO TO  ACCOUNT SETTINGS.<br />
  5.<strong>Current  Information Required </strong>. YOU MUST PROVIDE CURRENT, COMPLETE AND ACCURATE  INFORMATION FOR YOUR BILLING ACCOUNT. YOU MUST PROMPTLY UPDATE ALL INFORMATION  TO KEEP YOUR BILLING ACCOUNT CURRENT, COMPLETE AND ACCURATE (SUCH AS A CHANGE  IN BILLING ADDRESS, CREDIT CARD NUMBER, OR CREDIT CARD EXPIRATION DATE), AND  YOU MUST PROMPTLY NOTIFY US OR OUR PAYMENT PROCESSOR IF YOUR PAYMENT METHOD IS  CANCELED (E.G., FOR LOSS OR THEFT) OR IF YOU BECOME AWARE OF A POTENTIAL BREACH  OF SECURITY, SUCH AS THE UNAUTHORIZED DISCLOSURE OR USE OF YOUR USER NAME OR  PASSWORD. CHANGES TO SUCH INFORMATION CAN BE MADE AT ACCOUNT SETTINGS. IF YOU  FAIL TO PROVIDE ANY OF THE FOREGOING INFORMATION, YOU AGREE THAT WE MAY  CONTINUE CHARGING YOU FOR ANY USE OF THE SERVICE UNDER YOUR BILLING ACCOUNT  UNLESS YOU HAVE TERMINATED YOUR SUBSCRIPTION FOR THE SERVICE AS SET FORTH  ABOVE.<br />
  6.<strong>Change  in Amount Authorized. </strong>If the amount to be charged to your Billing Account  varies from the amount you preauthorized (other than due to the imposition or  change in the amount of state sales taxes), you have the right to receive, and  we shall provide, notice of the amount to be charged and the date of the charge  before the scheduled date of the transaction. Any agreement you have with your  payment provider will govern your use of your Payment Method. You agree that we  may accumulate charges incurred and submit them as one or more aggregate  charges during or at the end of each billing cycle.<br />
  7.<strong>Auto-Renewal </strong>. Unless you opt out of auto-renewal, which can be done through your  Account Settings, your subscription to the Services will be automatically  extended for successive renewal periods of the same duration as the  subscription term originally selected, at the then-current non-promotional  subscription rate. To change or resign your subscription at any time, go to  Account Settings. If you terminate your subscription, you may use your  subscription until the end of your then-current subscription term; your  subscription will not be renewed after your then-current term expires. However,  you won't be eligible for a prorated refund of any portion of the subscription  fee paid for the then-current subscription period.<br />
  8.<strong>Reaffirmation  of Authorization </strong>. Your non-termination or continued use of the Services  reaffirms that we are authorized to charge your Payment Method. We may submit  those charges for payment and you will be responsible for such charges. This  does not waive our right to seek payment directly from you. Your charges may be  payable in advance, in arrears, per usage, or as otherwise described when you  initially subscribed to the Services.<br />
  9.<strong>Free  Trials and Other Promotions. </strong>Any free trial or other promotion that  provides subscriber-level access to the Services must be used within the  specified time of the trial. You must cancel your subscription before the end  of the trial period in order to avoid being charged a subscription fee. If you  cancel prior to the end of the trial period and are inadvertently charged for a  subscription, please contact us at Support@whereweallmeet.com.<br />
  10.<strong>Mobile  Applications </strong>. Mobile functionality of the Services may be provided for  free, but please be aware that your carrier's normal rates and fees, such as  message and data rates, may still apply and you are solely responsible for  those fees. To the extent necessary, in the event you change or deactivate your  mobile telephone number, you agree that you will update your account  information within 48 hours to ensure that your messages are not sent to the  person who acquires your old number.</p>
<p>  9.<strong>Interaction  with Us or Our Agents </strong>. </p>
<p>We may provide assistance and guidance to users and  Members through our employees or agents. When communicating with those  individuals, you may not be abusive, obscene, profane, offensive, sexist,  threatening, harassing, racially offensive, or otherwise behave  inappropriately. If we feel that your behavior toward any of our customer care  representatives or other employees is at any time threatening or offensive, we  reserve the right to immediately terminate your membership.</p>
<p>  10.<strong>Termination</strong>.<strong></strong></p>
<p>1.<strong>By  Member</strong>. You may terminate your membership and/or subscription at any time,  for any reason, by following the instructions in your Settings or by sending  written notice of termination to Whereweallmeet.com, 5940 S. Rainbow Blvd., Las  Vegas, NV 89118 or email notice of termination to support@whereweallmeet.com<br />
  2.<strong>By  Us</strong>. We, at our sole discretion, may terminate your membership and/or  subscription for any reason or no reason. We are not required to provide you  notice prior to terminating your membership and/or subscription. We are not  required, and may be prohibited, from disclosing a reason for the termination  of your account.<br />
  3.<strong>Subscriptions</strong>.  If you terminate your subscription, your subscription will remain active until  the end of your then-current subscription period (that is, the subscription  period through which you had paid prior to your termination). <strong>If we  terminate your membership because you have breached these Terms, you will not  be entitled to any refund of unused subscription fees.</strong></p>
<p>  11.<strong>Disclaimers/Limitations</strong>.<strong></strong></p>
<p>  1.We  are not responsible for any incorrect or inaccurate content posted through the  Services, whether caused by users, Members or by any of the equipment or  programming associated with or utilized in the Services.<br />
  2.We assume no responsibility for any error, omission, interruption,  deletion, defect, delay in operation or transmission, communications line  failure, theft or destruction or unauthorized access to, or alteration of, user  or Member communications.<br />
  3.We  are not responsible for any problems or technical malfunction of any telephone  network or lines, computer online systems, servers or providers, computer  equipment, software, failure of email or players on account of technical  problems or<br />
  traffic congestion on the Internet or at any  website or combination thereof, including injury or damage to users and/or  Members or to any other person's computer related to or resulting from  participating or downloading materials in connection with the Services.<br />
  4.Under  no circumstances will we or any of our affiliates, advertisers, promoters or  distribution partners be responsible for any loss or damage, including personal  injury or death, resulting from use of the Services, any content posted on the  Services or transmitted to Members, or any interactions between users, whether  online or offline.<br />
  5.From  time to time, we may offer new &quot;beta&quot; features or tools with which  its users may experiment with the Services. Such features or tools are offered  solely for experimental purposes and without any warranty of any kind, and may  be modified or discontinued at our sole discretion.<br />
  6.We  provide the SERVICES &quot;AS IS, AS AVAILABLE,&quot; without any warranty or  condition of any kind (express, implied or statutory) AND YOUR ACCESS OF the  site IS AT YOUR OWN RISK. We do not warrant that our services will meet your  requirements or result in any particular outcome, or that the operation will be  uninterrupted or error-free. To the fullest extent allowed by law, we  specifically disclaim any implied warranties of title, merchantability,  non-infringement and fitness for a particular purpose. SOME STATES DO NOT ALLOW  THE DISCLAIMER OF IMPLIED WARRANTIES, SO THE FOREGOING DISCLAIMER MAY NOT APPLY  TO YOU.<br />
  7.We  shall not be liable to you for any DIRECT, special, incidental, indirect, punitive  or consequential damages (even if you have advised us of the possibility of  such damages). Our cumulative liability relating to your use of the SERVICES  (regardless of the basis), shall not exceed the greater of (a) amounts that you  PAID TO US IN THE PREVIOUS TWELVE MONTHS and (b) $100. SOME states do not allow  the exclusion or limitation of incidental or consequential damages, so the  above limitation or exclusion may not apply to you.</p>
<p>  12.<strong>Third  Party Links </strong>. </p>
<p>You may be provided links to other websites or resources  through the Services. Because we have no control over such sites and resources,  you acknowledge and agree that we are not responsible for the availability of  such external sites or resources, and do not endorse and are not responsible or  liable for any content, advertising, products or other materials on or  available from such sites or resources. You further acknowledge and agree that  we shall not be responsible or liable, directly or indirectly, for any damage  or loss caused or alleged to be caused by or in connection with the use of, or  reliance upon, any such content, goods or services available on or through any  such site or resource.</p>
<p>  13.<strong>Compliance  with Laws </strong>. </p>
<p>You will only use the Services in a manner consistent with  these Terms and any and all applicable local, state, national and international  laws and regulations, including, but not limited to, United States export  control laws. You represent and warrant that you are not located in, under the  control of, or a national or resident of any country which the United States  has (a) embargoed goods, (b) identified as a &quot;Specially Designated  National,&quot; or (c) placed on the Commerce Department's Table of Deny  Orders. Registration for, and use of, the Services are void where prohibited. To  the extent that the Services are not legal in your jurisdiction, you may not  use the Services; the Services may not be used where prohibited by law.</p>
<p> 14.<strong>Jurisdiction  and Choice of Law </strong>. </p>
<p>If there is any dispute arising out of the Services, by  using the Services you expressly agree that any such dispute shall be governed  by the laws of the State of Nevada, without regard to its conflict of law  provisions, and you expressly agree and consent to the exclusive jurisdiction  and venue of the state and federal courts of the State of Nevada, in Clark  County, for the resolution of any such dispute.</p>
<p>  15.<strong>Indemnity  by You </strong>. </p>
<p>You agree to indemnify and hold us, our subsidiaries, affiliates,  officers, agents, and other partners and employees, harmless from any loss,  liability, claim, or demand, including reasonable attorney's fees, made by any  third party due to or arising out of your use of the Services in violation of  these Terms and/or arising from a breach of these Terms and/or any breach of  your representations and warranties set forth above.</p>
<p>  16.<strong>Miscellaneous </strong>.<strong></strong></p>
<p>  1.<strong>Entire Agreement </strong>. These Terms contain the entire agreement  between you and us regarding the use of the Services.<br />
  2.<strong>Severability </strong>. If any provision of these Terms is held to be invalid, illegal or  unenforceable in any respect, that provision shall be limited or eliminated to  the minimum extent necessary so that these Terms shall otherwise remain in full  force and effect and enforceable.<br />
  3.<strong>Survival </strong>. Even after your membership or subscription is terminated, or your use of  the Services discontinues, these Terms will remain in effect. All terms that by  their nature may survive termination of these Terms shall be deemed to survive  such termination.<br />
  4.<strong>Waiver </strong>. Our failure to enforce any part of these Terms shall not constitute a waiver  of our right to later enforce that or any other part of these Terms. Waiver of  compliance in any particular instance does not mean that we will do so in the  future. In order for any waiver of compliance with these Terms to be binding,  we must provide you with written notice of such waiver, provided by one of our  authorized representatives.<br />
  5.<strong>Headings </strong>. The section and paragraph headings in these Terms  are for convenience only and shall not affect the interpretation of these  Terms.<br />
  6.<strong>No Third Party Beneficiaries </strong>. You agree that, except as  otherwise expressly provided in these Terms there shall be no third party  beneficiaries.<br />
  7.<strong>Relationship of the Parties </strong>. You and we are independent  contractors, and no agency, partnership, joint venture, employee-employer or  franchisor-franchisee relationship is intended or created by these Terms.<br />
  Please contact us at <a href="mailto:support@themanyouwant.com">support@whereweallmeet.com </a>with any questions regarding these Terms. WhereWeAllMeet.com  is a service mark of The Man You Want, LLC., all rights reserved.<br />
  I HAVE READ THESE TERMS AND AGREE TO ALL OF THE  PROVISIONS CONTAINED ABOVE.</p>
